name: 'VTEX App Metadata Action'
description: 'Reads metadata from a VTEX app'
outputs:
  app-id:
    description: "App id"
  app-name:
    description: "App name"
  current-app-version:
    description: "Current app version, which is used to determine the next-app-version"
  next-app-version:
    description: "Next app version, which will be used in the built artifacts"
  current-app-specification:
    description: "App specification in JSON format using current-app-version"
  next-app-specification:
    description: "App specification in JSON format using next-app-version"
  vendor-id:
    description: "Vendor id"
  service-name:
    description: "Service name"
  service-folder:
    description: "Service folder"
  service-image-name:
    description: "Service image name"
runs:
  using: 'node12'
  main: 'dist/index.js'
